### ISSUE TITLE
Make the explorer responsive

### ISSUE THREAD

**Issue by carlosmmelo** [bwang22/xsnblockexplorer#4]
Add responsive CSS for mobile access:

**Comment by carlosmmelo** [comment]
![image](https://user-images.githubusercontent.com/5649650/38788423-8e9f2bc0-4101-11e8-91bb-4ca4195c12b6.png)

**Comment by AlexITC** [comment]
The ticker boxes could be rendered one per line, how would you render the table?

**Comment by AlexITC** [comment]
The boxes are now rendered 1 or 2 per row on smaller screens, as you never answered about the table, I'm closing the ticket.
